replicaCount: 1
image:
  tag: "1.0" 
app:
  content: "hello world"
  message: "your personal message here..."
  port: 8080
ingress:
    enabled: true
    ## List of hosts for the ingress
    host: hello-world-configmap.n-able.xyz